### ISSUE TITLE
Exit button?

### ISSUE THREAD

**Issue by alxwrd** [alxwrd/school-timer#3]
Could potentially add an exit button which closes the tab.

**Comment by jmsv** [comment]
I started looking into this although modern browsers don't support closing a window that wasn't originally opened by a script (presumably due to misuse) so this can't really be done. See: https://stackoverflow.com/q/19761241/5127934

There are a few hacky workarounds (such as just wiping the window contents) but this isn't a solution if the tab is supposed to close

Should the 'Close' button be removed?

**Comment by alxwrd** [comment]
Thanks for the investigation! I hadn't looked into this after opening the issue.

This used to be an Electron app so that's why it's there, but yea, close should probably go if that's the case.

**Comment by jmsv** [comment]
ah that makes sense, good ol' electron apps
